IF OBJECT_ID ('dbo.Group') IS NOT NULL
	DROP TABLE dbo.Group
GO

CREATE TABLE [Group]
(
	GroupID INT IDENTITY NOT NULL,
	Title NVARCHAR(100) NOT NULL UNIQUE,
	CreatedBy INT NULL,
	Description NVARCHAR(500) NULL,

	CONSTRAINT PK_Group PRIMARY KEY (GroupID ASC)
)
GO